### ISSUE TITLE
Inconsistent usage of Intermediate-Directory in Python Scripts

### ISSUE THREAD

**Issue by dorvak** [akirmse/mountains#20]
The usage of the intermediate_dir Args Parameter in the run_glo_prominence.py-Script is inconsistent and should be modified like this in order to pick up right (modified) variable:

`prom_command = f"{args.prominence_command} --v=1 -f {args.format}" + \
        f" -i {**intermediate_dir**} -o {args.output_dir}" + \
        f" -t {args.threads} -m {args.min_prominence}"`

**Comment by akirmse** [comment]
Fixed by 04729914c36ca02293013d7119a856440d144e71.  Thanks!
