### ISSUE TITLE
Custom DTM data

### ISSUE THREAD

**Issue by zdila** [akirmse/mountains#23]
Hello,

Is it possible to use custom DTM geotiff file? Should it be in a specific projection? Or can I convert it to something that your app will understand? And can this program detect if it requires data outside provided region to compute the prominence?

Thank you.

**Comment by zdila** [comment]
Great, thanks!

I have single big GeoTIFF of Slovakia in 1 m horizontal resolution and EPSG:8353. Could you please give me a hint how to retile it (probably with `gdal_retile`) so that `prominence` tool would understand it? I guess the format then should be 3DEP-1M.

If not then I will try to cope with it myself  somehow :-).

**Comment by anbj** [comment]
@zdila, I think we want the same thing (see my #22).

Your suggestions with gdal_retile got me thinking, and got me a *bit* closer to my goal as well.
I'm using GLO30 'template'.

* Get your grid. Make sure the width and height is at least 2400 x 3600; this is the expected tile size of GLO30.
* Retile with ``gdal_retile.py -of EHdr -ot Float32 -ps 2400 3600 nore.nc -targetDir tile``
* You'll now (maybe) have a bunch of tiles in `tile/`. These will have a .bil file extension.
* Rename to GLO30 naming scheme (and note extension; flt), e.g. Copernicus_DSM_COG_10_N58_00_E005_00_DEM.flt. You might have change the coordinates to fit your region.
* Run ``prominence``, e.g. `prominence --v=4 -f "GLO30" -i tile -o out 58 60 5 6`.
* I got `prominence` running this way, but since I had to manipulate my original grid (this is for testing only), I think the coordinates was messed up. Anyway, at least this is a start.

**Comment by akirmse** [comment]
Hi guys, I'm back from vacation.  Have you made progress on this, or is there something I can help with?  I don't have experience with gdal_retile but I can try it out if you have some sample data to point me to.

**Comment by anbj** [comment]
Welcome back! Not really. I tried what I described in https://github.com/akirmse/mountains/issues/23#issuecomment-1666118886, but it *seems* like ``prominence`` is using (lon,lat) deduced from the tile name (in my case, a fake tile name - I have to trick ``prominence``). Could you comment on that?

**Comment by anbj** [comment]
Oh, I’m sorry - I attached a file in the post; *BathymetryExport-drm.zip*. It blends in with the link, så hard to see.

**Comment by akirmse** [comment]
This data is pretty far from the nice 1 degree by 1 degree terrain data I've worked with so far.  It's in UTM, and it's a strange shape:

```
gdalinfo BathymetryExport-dtm.tif

Size is 1139, 839
Coordinate System is:
PROJCRS["ETRS_1989_UTM_Zone_33N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101004,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],

Corner Coordinates:
Upper Left  (  222775.000, 8224775.000) (  5d59'54.28"E, 73d55'34.15"N)
Lower Left  (  222775.000, 8182825.000) (  6d11'52.13"E, 73d33'16.76"N)
Upper Right (  279725.000, 8224775.000) (  7d49'36.15"E, 73d59'42.65"N)
Lower Right (  279725.000, 8182825.000) (  7d59'11.56"E, 73d37'19.32"N)
Center      (  251250.000, 8203800.000) (  7d 0' 5.35"E, 73d46'35.19"N)
```

The FLT file format throws away all of this necessary metadata.  In the common terrain formats like GLO30, SRTM, etc., the corner coordinates and resolution are implicit in the filename (like "n39_w122.flt" or whatever), and the name of the format.  So this will take some doing.

One possibility is using GDAL tools to change the projection, and then tile to one-degree increments.  I don't have experience with this but I will take a look.  Another possibility is to change the projection, then feed in all of the metadata via command-line parameters.

The prominence program is designed to process tiles in parallel, and in particular, the algorithm requires absolutely perfect seams between the tiles.  The tiles must have at least one pixel of overlap, and those values must be exactly equal in neighboring tiles.  I found that even USGS tiles that claim to have equal values do not, so the prominence program actually reads in one row and column of neighboring tiles to force the values to be equal.  All this is to explain why the program needs to know how to form the filename for a neighboring tile given the corner coordinates; you can't just throw a bunch of random filenames at it.  If this is going to be a recurring or large-scale need, you'll want to write a Python driver program to automate the tiling and renaming (much as I've done for other formats in the scripts directory).

**Comment by anbj** [comment]
Thanks @akirmse for great tips and hints.
Will play with this when time permits.

**Comment by akirmse** [comment]
I've recently developed a script that will retile arbitrary source data to 1m resolution and run the prominence code on it.  It's checked in at https://github.com/akirmse/mountains/blob/master/scripts/run_lidar_prominence.py.  @zdila I recently ran across the DTM 5.0 for Slovakia and I would be very interested in running a prominence analysis on it.  However, it's a single 183 GB file that might be difficult for me to download.  If you already have this data I would be happy to help you with the operation of the script.

**Comment by zdila** [comment]
@akirmse if it is simple to run then I can try. Could you please post me the instructions so I don't need to deep dive into it? Thank you.

**Comment by akirmse** [comment]
You will need Python and GDAL installed and in the path, and a lot of disk space.  Suppose you've forked the repo into "directory".  Then try:

- Go into ```<directory>/code```
- Run ```make RELEASE=1``` (```nmake -f makefile.win RELEASE=1``` on Windows) to build the prominence tools
- Go someplace where you have a lot of disk space
- Run
```
python <directory>/scripts/run_lidar_prominence.py --binary_dir <directory>/release --threads 6  <path to data>/*.tif
```

(Assuming your machine has at least 6 cores; you can go higher if you have more and a fast disk.)

This will compute everything down to 100m of prominence and put it in the file prominence/results.txt.  It could take a long time to run depending on the size of the input.  You can change much of the behavior with flags (run with ```--help``` to see).

No one else has tried this yet so let me know if you see problems.  I will add some better documentation in the README on github soon.

**Comment by anbj** [comment]
Any GDAL version requirement?

I'm getting  ```
$ python3 mountains/scripts/run_lidar_prominence.py --binary_dir mountains/release --threads 6 Downloads/*.tif
Creating VRTs and computing boundary
Projection 1: ETRS89 / UTM zone 33N
  Creating VRTs
0...10...20...30...40...50...60...70...80...90...100 - done.
Data has no overviews; using full resolution (slow)
  Computing boundary
Traceback (most recent call last):
  File "/home/anbj/mountains/scripts/run_lidar_prominence.py", line 316, in <module>
    main()
  File "/home/anbj/mountains/scripts/run_lidar_prominence.py", line 247, in main
    warped_vrt_filename, bounds = create_vrts(args.tile_dir, input_files,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anbj/mountains/scripts/run_lidar_prominence.py", line 165, in create_vrts
    footprint_options = gdal.FootprintOptions(
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'osgeo.gdal' has no attribute 'FootprintOptions'
```

**Comment by akirmse** [comment]
Looks like that requires GDAL 3.8.0.

**Comment by anbj** [comment]
Thanks. Will have to compile GDAL from source and try.

**Comment by zdila** [comment]
It failed for me:
```
Running prominence
> mountains/release/prominence --v=1 -f LIDAR -i tiles -o prominence -t 24 -m 33.333333333333336 -- 47.7 49.7 16.8 22.6
/bin/sh: 1: mountains/release/prominence: not found
Running merge
> mountains/release/merge_divide_trees --v=1 -f -t 24 -m 100 -s 1 prominence/results prominence/*_*.dvt
/bin/sh: 1: mountains/release/merge_divide_trees: not found
```

I think the path in sripts is wrong and missing `code` directory.

**Comment by anbj** [comment]
Change the `` --binary_dir <directory>/release`` to the correct path.
I clone the repo to ~, and then it should be `` --binary_dir <directory>/code/release``.

**Comment by zdila** [comment]
Will the script continue from where it failed or will it start from beginning (and I should rather delete generated files)?

**Comment by anbj** [comment]
I think it re-runs everything.

**Comment by anbj** [comment]
Well, you could run those commands manually.

**Comment by zdila** [comment]
The result: https://drive.google.com/drive/folders/1iWS5Vz-qh5mPQ4pO1itYuCoei3Sprk1e?usp=sharing

Is it that KML file? There are not many peaks.

**Comment by akirmse** [comment]
I'll fix the default for the --binary_dir flag, sorry about that.

The results are in results.txt, which I like to preview by loading into Google Earth (File -> Import).  However, there are a few obviously wrong things with your output:

- Prominence ran on only every degree boundary, instead of every tenth of a degree.  I'm not sure how that's possible.
- There are some "peaks" with outrageous elevations like 1e38, which suggests either a problem with the input, or with how its nodata values are configured.

Is it possible for you to post your command line and the entire output, or perhaps you can point me to where I can get the input data you used, so that I can try it locally?

**Comment by zdila** [comment]
You can download DTM of whole Slovakia from https://www.geoportal.sk/en/zbgis/airborne-laser-scanning/als-products-providing/provision-als-products.html (1st project cycle (2017 – 2023), DMT 5.0) .

I've used S-JTSK[JTSK03]+HBpv version.

After creating overviews with gdaladdo I've run it like this:

GTIFF_SRS_SOURCE=EPSG nice python mountains/scripts/run_lidar_prominence.py --binary_dir mountains/release --threads 24 dmr5_jtsk03.tif

Afterwards I ran those 2 command manually.

Unfortunately I don't have the whole output available, just last ~10k lines, but most of them say

```
2024-03-21 12:50:01,140 INFO [default] Removed possible spike at 49.5105, 18.5772
```

**Comment by zdila** [comment]
BTW you can see hillshading of this DTM (translated to EPSG:3857) at https://www.freemap.sk/#map=8/48.707140/19.499500&layers=5

Or see it smoothed on the outdoor map at https://www.freemap.sk/#map=8/48.707140/19.499500&layers=X

**Comment by akirmse** [comment]
The whole country is a single zipped 138GB file?  That might be tough for me to download from the U.S., and it might take some time, but I will try.

Can you post your file tiles/boundary.shp?  That's the auto-generated boundary of the data set, which might give some clues.

The messages about spikes in the data are concerning.  I would not expect Lidar data to have big ~100m spikes in it.

**Comment by zdila** [comment]
You can export (much) smaller areas with https://zbgis.skgeodesy.sk/mkzbgis/en/teren/export?pos=48.744174,20.344716,16

I've just put the boundary shapefiles to the same gdrive folder.

> The messages about spikes in the data are concerning. I would not expect Lidar data to have big ~100m spikes in it.

There should be no such spikes. The data are of very good quality.

<details>
  <summary>For sure ehre is also gdalinfo of the input file</summary>
   <code>Driver: GTiff/GeoTIFF
Warning 1: The definition of projected CRS EPSG:8353 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.
Files: dmr5_jtsk03.tif
       dmr5_jtsk03.tif.ovr
Size is 429324, 205067
Coordinate System is:
ENGCRS["S_JTSK_JTSK03_Krovak_East_North",
    EDATUM["Unknown engineering datum"],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    ID["EPSG",8353]]
Data axis to CRS axis mapping: 1,2
Origin = (-594412.999900000868365,-1132309.999899999704212)
Pixel Size = (1.000000000000000,-1.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -594413.000,-1132310.000) 
Lower Left  ( -594413.000,-1337377.000) 
Upper Right ( -165089.000,-1132310.000) 
Lower Right ( -165089.000,-1337377.000) 
Center      ( -379751.000,-1234843.500) 
Band 1 Block=128x128 Type=Float32, ColorInterp=Gray
  Min=93.180 Max=2654.530 
  Minimum=93.180, Maximum=2654.530, Mean=450.155, StdDev=310.902
  NoData Value=3.4e+38
  Overviews: 214662x102534, 107331x51267, 53666x25634, 26833x12817, 13417x6409, 6709x3205, 3355x1603, 1678x802, 839x401, 420x201, 210x101
  Unit Type: metre
  Metadata:
    RepresentationType=ATHEMATIC
    STATISTICS_COVARIANCES=96659.88643438072
    STATISTICS_MAXIMUM=2654.5300292969
    STATISTICS_MEAN=450.15522061848
    STATISTICS_MINIMUM=93.180000305176
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=310.90173115372
   </code>
</details>

**Comment by zdila** [comment]
> There are some "peaks" with outrageous elevations like 1e38, which suggests either a problem with the input, or with how its nodata values are configured.

Probably nodata? Please see my gdalinfo output above.

**Comment by akirmse** [comment]
Yes, that nodata value wasn't being handled correctly.  I've checked in a change to the script that coverts the nodata value, which will get rid of those spike messages and bad output.

I'm not sure why the calculated boundary you posted is empty.  I exported a small region from that like you sent, and it processed fine, including a correct boundary polygon.  I also see that GDAL warning about the unknown projection, which needs to be worked around via an environment variable.  I suppose my next step is to download the whole data set.  

You could try re-running with the fixed script.  I expect that most of the output tiles will still be missing because the boundary is empty.  If that happens, as a temporary workaround you could run with the --skip_boundary flag.  That will skip producing the boundary (using just a simple rectangle instead), at the expense of using more disk space for extra output tiles that will turn out to be completely empty.

**Comment by zdila** [comment]
I've tried `git pull; GTIFF_SRS_SOURCE=EPSG nice python mountains/scripts/run_lidar_prominence.py --skip_boundary --binary_dir mountains/code/release --threads 24 dmr5_jtsk03.tif` but the results are not better. See subfolder `attempt2` in the shared drive.

In `output.txt` you will find complete console output.

**Comment by akirmse** [comment]
I was able to download the DEM, and then I ran (on Windows): 
```
python c:\mountains\scripts\run_lidar_prominence.py  --binary_dir c:\mountains\code\release --threads 6 --min_prominence 100 source\dmr5_0\*.tif
```

After about 3 hours I got the attached file, which has all the peaks of 100 meters prominence or more.
[results.txt](https://github.com/akirmse/mountains/files/14727506/results.txt)  You can visualize this by loading it into Google Earth (File -> Import) or other tools.

As always, peaks whose key saddles are outside the data area will be wrong; their prominence will be too large.  This will generally affect peaks near the border, and the high point of the data area.

Some things for you to check on your side:

- Double-check that you have all the latest code and have rebuilt the C++ code.
- I have GDAL 3.8.3, though I believe anything 3.8.0+ should work.
- Look at tiles/boundary.shp (e.g. in QGIS or Google Earth) and verify that it looks like the outline of Slovakia.
- You're running with 24 threads, which will require a lot of memory, at least 32 GB.  If you don't have that much, maybe some of the processes are failing (I should add an error message for this case).

**Comment by zdila** [comment]
Thank you for the results :-).

I use regularly updated Debian testing. My GDAL version is  3.8.4. My RAM is 64GB (+ 50GB of swap).

If I have a time I can try playing with it again. BTW I have whole DTM of slovakia as a single TIFF file.

> As always, peaks whose key saddles are outside the data area will be wrong; their prominence will be too large. This will generally affect peaks near the border, and the high point of the data area.

Would it be possible to implement marking such peaks so that one could know that their prominence value is incorrect?

**Comment by akirmse** [comment]
> Would it be possible to implement marking such peaks so that one could know that their prominence value is incorrect?

I'm not sure.  It's on my list to investigate.

**Comment by zdila** [comment]
Could you please share kml file? I tried to import that txt but Google Earth reports error.

**Comment by akirmse** [comment]
The KML is a debugging version of the final divide tree; it's not useful for getting the list of peaks.

results.txt is a simple CSV that you can import into Google Earth (https://mapscaping.com/importing-csv-files-into-google-earth/) or QGIS (https://www.qgistutorials.com/en/docs/importing_spreadsheets_csv.html) among other tools.

**Comment by akirmse** [comment]
I've thought some more about the problem of identifying peaks whose saddles are known to be inside the data, versus those whose saddles might be outside.  This is difficult with e.g. the Slovakia data, because the provided DEM has "nodata" values all around the outside, implying that Slovakia is an island without any neighboring terrain.  If Slovakia were in fact an island, the DEM would look identical to this, and all of the saddles would be inside the data set.  So to distinguish these two cases, I'll have to come up with a behavioral change, as well as an optional flag that tells the system whether the data is or is not surrounded by land.

**Comment by akirmse** [comment]
I'm also going to close this issue, as I've successfully handled many arbitrary data sets with this script, including the original Slovakia request.
