### ISSUE TITLE
Add support for SRTM 1''

### ISSUE THREAD

**Issue by anbj** [akirmse/mountains#25]
As far as I can tell, **prominence** et al. only support the 3'' resolution (90 m) dataset of SRTM.

Would it be possible to support the 1'' resolution as well?

**Comment by akirmse** [comment]
I could take a look at this.

The GLO-30 dataset is the same resolution (30m), newer, and already has
support.  Would that work for you?

**Comment by anbj** [comment]
Yes, it might. I'll check that option out. Thank you!

PS! If you're feeling "done" with this project, please let me know and I'll stop annoying you.

**Comment by akirmse** [comment]
Definitely not done---there's always better data!  One day everything will
be Lidar, and this code will have to adapt.

**Comment by anbj** [comment]
Going to try to GLO-30 if I need 1''.
