### ISSUE TITLE
merge_divide_trees: features in KML and TXT output

### ISSUE THREAD

**Issue by anbj** [akirmse/mountains#26]
The contents of *merged.txt* is identical, but the contents of *merged-divide_tree.kml* differs when running **merge_divide_trees** with or without ``-f``. Is this expected? Note I'm only checking **Peaks** in the KML-file.

```
$ merge_divide_trees merged prominence-72x00-002x00-divide_tree_pruned_0.dvt
```

```
$ ogrinfo -so merged-divide_tree.kml Peaks
INFO: Open of `merged-divide_tree.kml'
      using driver `LIBKML' successful.

Layer name: Peaks
Geometry: Unknown (any)
Feature Count: 145       <--------------
[...]

```
```
$ wc merged.txt 
  66   66 3036 merged.txt
```

Now lets run again with ``-f``:
```
$ merge_divide_trees -f merged prominence-72x00-002x00-divide_tree_pruned_0.dvt
```
```
$ ogrinfo -so merged-divide_tree.kml Peaks
INFO: Open of `merged-divide_tree.kml'
      using driver `LIBKML' successful.

Layer name: Peaks
Geometry: Unknown (any)
Feature Count: 70       <--------------
[...]
```

```
$ wc merged.txt 
  66   66 3036 merged.txt
```

**Comment by akirmse** [comment]
Yes, this is expected.  -f deletes the "runoffs", which are intermediate entities that are needed if the output is to be merged further.  You can read more about runoffs at https://www.andrewkirmse.com/prominence.

The KML output is mostly for debugging purposes.  Maybe I should default to not generating it.

**Comment by anbj** [comment]
Thank you, and sorry for posing questions that I should be able to figure out myself.
I've read your posts about this, I just need to grasp it.

I've been able to create a routine that takes ``(x,y,z)``, resamples and processes the data into a grid that ``prominence`` and WinProm can use. Very exciting.

Oh, and one more thing; I just processed a tile, and was very surprised that the highest point in my tile, was not included in the final data set. Need to look at it some more, but do you have any idea if this would be an issue if the input grid contains only negative numbers? This is bathymetry, so z < 0.

**Comment by akirmse** [comment]
Hm, yes, that's true, there's not really a well-defined prominence value for the highest point < 0.  For Everest, using the elevation matches intuition as the high point of a land mass, but I don't know what the right answer is for bathymetry.

**Comment by anbj** [comment]
* Ref. my [post](https://github.com/akirmse/mountains/issues/26#issuecomment-1881158393) above, I'm a bit puzzled.
* Without introducing my own confused musings on this, here's a note.
* I have generated an 'SRTM pseudo tile' based on data from various sources. All is bathymetry, so ``z < 0``. The region is 2E-3E, 72-73N. 
* Since the highest peak, based on eyeballing, is missing, I thought it may have something to do with the negative ``z``'s.
* I took my original grid and **added 4000 to the z-value**. 4000 was arbitrarily chosen, just to get all ``z > 0``.
* Here's screenshot of a run with the original grid (``z < 0``). From the kml-file:
![org-kml](https://github.com/akirmse/mountains/assets/29237824/c64cf261-b885-4d6c-9a31-f9f87e630711)

* And the resulting txt-file:
![org-txt](https://github.com/akirmse/mountains/assets/29237824/edfab6f1-867d-43f8-84a9-3d0b17282360)


* And here's a screenshot of a run with the shifted grid (``z > 0``). From the kml file:
![shifted-kml](https://github.com/akirmse/mountains/assets/29237824/be77d4f3-f7ea-4da4-aab4-278fb4b7400f)
* And the resulting txt-file:
![shifted-txt](https://github.com/akirmse/mountains/assets/29237824/81b41ab3-6ae0-476c-aec0-31467f9f30ba)

* If you *want* to do your own run, I'm attaching the files.
[files.zip](https://github.com/akirmse/mountains/files/14065497/files.zip)

    * N72E002-original.hgt - original file, ``z < 0``.
    * N72E002-shifted.hgt - shifted (+4000) file, ``z > 0``.

**Comment by akirmse** [comment]
I ran the following two commands on each input tile:
```
\mountains\code\release\prominence.exe -f SRTM 72 73 2 3 
\mountains\code\release\merge_divide_trees -f output prominence-72x00-002x00-divide_tree_pruned_100.dvt
```

What I found is similar to what you're seeing.  The shifted version has two additional output points.  One is the dataset high point, which is expected to be missing in the output for the original tile, because as we discussed, it's not clear what the prominence of that point is when the data is all negative.  But the other looks like it may be a bug.  I'm investigating.

(Note that since we didn't specify a min prominence, the default value of 100 was used.  Also, I ran merge_divide_trees with the -f flag, which removed points around the boundary that don't have sufficient prominence within the tile, but which might if the tile were merged with neighbors.  I did that just to reduce the number of points I had to look at.)

**Comment by anbj** [comment]
Thanks!

And sorry for not including the commands I ran. I think it was the default value for min. prominence (i.e. 100).

**Comment by akirmse** [comment]
I did some careful debugging and did see a tiny difference in one calculation that I couldn't explain.  I did a diff of the two rasters in QGIS and found that most corresponding pixels have a difference of 4000, but a non-trivial number (a few hundred) have a difference of 4001.  That might or might not explain the prominence difference, but it does make debugging extremely difficult.  Is it possible this is due to floating point discrepancies in the shift you applied?

**Comment by akirmse** [comment]
It's also possible that QGIS is producing false positives due to floating point rounding.. just wanted to be sure you know that the two rasters are exactly 4000 apart everywhere.

**Comment by anbj** [comment]
Interesting. I'm using GMT's (https://www.generic-mapping-tools.org/) ``grdmath`` to shift the grid, and I don't think this should cause/introduce any floating point discrepancies, but who knows. I'll do some investigation.

Thanks for your interest in this!

**Comment by anbj** [comment]
You want me to close this?

**Comment by akirmse** [comment]
Up to you.. I haven't looked at it again.  I'd need to know more about how the shift of 4000 was done before investigating further, in case that's what introduced the discrepancy.

**Comment by anbj** [comment]
Thanks. I'll keep it open then. I hope to have more time to investigate at some point.

**Comment by anbj** [comment]
Very likely the same issue as in #43.
