### ISSUE TITLE
run_lidar_prominence.py input_file error

### ISSUE THREAD

**Issue by kylebreth** [akirmse/mountains#33]
I am having an issue with the run_lidar_prominence.py file. Whenever I try to run it, I get the error "Input filespec input_files matched no files; exiting." The thing is, the input file clearly does, in fact, exist at the path I specified.

Here's the command I'm using: 
"python /Users/<my name>/Downloads/mountains/scripts/run_lidar_prominence.py --input_units meters --output_units meters --output_dir /Users/<my name>/Downloads/prom_output --min_prominence 30 input_files /Users/<my name>/Downloads/DEM_tiles/USGS_OPR_WA_NorthCentral_2021_B21_11UQQ200180.tif"

I got the lidar file from: 
https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/OPR/Projects/WA_NorthCentral_2021_B21/WA_NorthCentral_3_2021/TIFF/USGS_OPR_WA_NorthCentral_2021_B21_11UQQ200180.tif

I have had success with running the run_3dep_prominence.py file so presumably everything was built fine, and my system meets the other requirements listed in the README as well. It's possible that I'm just being an idiot, but this does not seem like expected behavior.

Thanks for your work on this project!

**Comment by akirmse** [comment]
See the error message: it's looking for a file called "input_files".  Try
removing that from your command.

**Comment by kylebreth** [comment]
Wow - I feel very silly now. That worked beautifully.
