### ISSUE TITLE
3DEP TIFF file URLs

### ISSUE THREAD

**Issue by kylebreth** [akirmse/mountains#42]
Most of the URLs for 3DEP TIFF files have this general format: 'https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/WA_NorthCentral_2021_B21/TIFF/USGS_1M_11_x31y528_WA_NorthCentral_2021_B21.tif'. This is the format that your 3DEP python script assumes. 

However, I have run into a few datasets which are formatted differently - for example, 'https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/WA_3_County_QL1_2017/TIFF/USGS_one_meter_x39y513_WA_3_County_QL1_2017.tif'. Here, "one_meter" is spelled out and the UTM zone is not part of the URL, which causes the script to fail. I solved this problem by making a copy of the python script to use for this type of URL and editing the tif_url variable. It would be nice if your script handled this case though.

Thanks for your work on this project!

**Comment by akirmse** [comment]
With experience I found that there are too many variants of filenames to keep track of -- the 3DEP apparently doesn't have good standards.  And beyond that, it's possible for a single project to span multiple UTM zones, making processing areas that straddle the border impossible.  And beyond even that, I wanted to be able to process Lidar from other agencies to fill in the gaps in 3DEP, or handle data from other countries.

For all those reasons, I wrote the script [run_prominence.py](https://github.com/akirmse/mountains/blob/master/scripts/run_prominence.py).  It does a reprojection, so it takes more time and disk space, but on the other hand it can handle any format that GDAL knows about.  You can pass it simply ```*.tif``` and it will handle everything.  I've used it to process much of the U.S., and entire European countries.

**Comment by kylebreth** [comment]
That's fair. I do still wonder, though, if there could at least be better communication about this situation. Like maybe a note in the readme somewhere in case someone else is wondering why their syntactically correct 3dep script call isn't doing anything?

I do know about the run_prominence script, but I'll probably stick to my edited copy of the 3dep one because of the disk space benefit you mentioned as well as the convenience of just being able to enter a range of UTM coordinates and download the right .tif files automatically.

(for what it's worth, I wrote some code to look through the Rocky directory and found three different URL formats - the two I mentioned above, plus this type: https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1m/Projects/WA_Olympic_Peninsula_C2_2017/TIFF/USGS_1m_x46y515_WA_Olympic_Peninsula_C2_2017.tif)

**Comment by akirmse** [comment]
Thanks for the research.  It wasn't hard to just try all of these URL formats in sequence, so I've added that.

**Comment by kylebreth** [comment]
Awesome - thanks for making that update!
