### ISSUE TITLE
Quality checking results?

### ISSUE THREAD

**Issue by anbj** [akirmse/mountains#43]
Thank you so much for your time and effort working on this; it's awesome.

Do you have any good tips on how to quality check the results?
If you have thousands of prominence coordinates, how do you check that it's correct?

When eyeballing the map and results from promience, I always have to keep my tongue straight, but some things are strange. The plot below shows a bunch of prominence points (black dots). I've manually added some red rings in some areas (but not all!) indicating where I would expect there to be a prominence point, but there are none. This is all bathymetry, so the High Point closest to sea level (i.e. ``z = 0``) I kind of expect to be missing, ref my [other post](https://github.com/akirmse/mountains/issues/26#issuecomment-1881158393).

Are there any obvious reasons that **prominence** didn't find any prominence points in those red rings?!

![Screenshot from 2024-11-01 15-01-04](https://github.com/user-attachments/assets/03b61e2e-c17a-4035-8b01-34812d313c49)

Command, for reference:

```
run_prominence.py --skip_boundary --degrees_per_tile 1 --samples_per_tile 4444 --binary_dir=~/mountains/code/release inputgrid.nc
```

**Comment by akirmse** [comment]
It's hard for me to tell based on a screenshot.  Can you link to your data
so that I can try it locally?

I have pretty high confidence in above-zero results, as I've processed many
hundreds of thousands of peaks, including the whole Earth several times
over.  Maybe there's a problem related to negative values somewhere.

**Comment by anbj** [comment]
Absolutely.

Here is my grid file: https://www.dropbox.com/scl/fi/syovyzirhjsmbg8listqw/nosj.nc?rlkey=jxlhltz5f20nv42y09y96tigo&st=amk3bra9&dl=0

Command:
```
run_prominence.py --skip_boundary --degrees_per_tile 1 --samples_per_tile 4444 --binary_dir=~/mountains/code/release nosj.nc
```

**Comment by anbj** [comment]
I see now that the grid does not have projection information. This is WGS84/EPSG:4326. I thought gdal would complain about that, hmm.

**Comment by akirmse** [comment]
One thing I noticed is that the original DEM is only 10220 by 5490 pixels, and it spans a good part of the earth, so running with a setting of 4444 pixels per degree results in a massive oversampling.  I ran with --samples_per_tile 500 instead, and got the attached result.

Another thing I saw during the run was some output like this:
```
2024-11-01 10:40:01,788 INFO [default] Removed possible spike at 60.958, 6.988
2024-11-01 10:40:01,788 INFO [default] Removed possible spike at 60.958, 6.99
2024-11-01 10:40:01,789 INFO [default] Removed possible spike at 60.866, 6.838
2024-11-01 10:40:01,789 INFO [default] Removed possible spike at 60.866, 6.84
2024-11-01 10:40:01,790 INFO [default] Removed possible spike at 60.854, 6.812
2024-11-01 10:40:01,790 INFO [default] Removed possible spike at 60.854, 6.814
```

The code has some automatic detection to attempt to remove single-sample "spike" elevation errors that are commonly found in terrain DEMs.  This detection is based on the difference of the sample's elevation with its neighbors.  However, your data is so low resolution that maybe this is too aggressive.  You could try commenting out the spike detection or setting the detection constant to something enormous (https://github.com/akirmse/mountains/blob/21fbbe0f612abe1224dfaf5fd2b03edc1ede412c/code/tile_cache.cpp#L99), and if that works, I could add a flag to disable it.

[results.txt](https://github.com/user-attachments/files/17602705/results.txt)

**Comment by anbj** [comment]
Your result was the same as mine.

I tried increasing MAX_LEGAL_ELEVATION_DIFF to something huge, and it didn't help. I also removed it, but still the same.

Here's another grid which covers an area with missing prominence points: [bat.nc](https://www.dropbox.com/scl/fi/otc86wla2ldhenk8694ni/bat.nc?rlkey=7z9y50jlc1z5liyg60fdel348&st=c88mfzt6&dl=0).

Make another version that adds 10000 so all z >> 0:

```
gdal_calc.py -A bat.nc --outfile=bat-pos.nc --calc="A+10000" --overwrite
```

Now run prominence for original:
```
run_prominence.py --skip_boundary --degrees_per_tile 1 --samples_per_tile 500 --binary_dir=~/mountains/code/release --threads $(nproc) --output_dir original-bat bat.nc
```

and for shifted (+10000):
```
run_prominence.py --skip_boundary --degrees_per_tile 1 --samples_per_tile 500 --binary_dir=~/mountains/code/release --threads $(nproc) --output_dir pos-bat bat-pos.nc
```

Plot this to see the differences:

![promtest](https://github.com/user-attachments/assets/7f4d7cd7-4103-4800-948a-8b7c2bdf878c)


Are the key saddles found before the prominence? Note that some key saddles for the original grid is not found, while they are for the shifted grid (green circle with no red outline).

Code for plot for own reference:

```
gmt begin promtest png; gmt grdimage bat.nc -t50 -JM16c; gmt grdcontour -C100 bat.nc -l"100m"; gmt plot original-bat/results.txt -St.4c -Gred -W -: -l"Original"; gmt plot pos-bat/results.txt -Sc.1c -Ggreen -W -: -l"+10000"; gmt plot pos-bat/results.txt -i4,3 -Sc0.2c -Ggreen -l"saddle_+10000"; gmt plot original-bat/results.txt -i4,3 -Sc0.2c -Wthick,red -l"saddle_original"; gmt end show
```

**Comment by akirmse** [comment]
Thanks, I can reproduce this here, and I have an idea of what's wrong.

**Comment by akirmse** [comment]
I found the bug: I was setting the prominence of the highest peak equal to its elevation, which is the normal convention for mountains.  But this doesn't work for underwater peaks; the resultant negative prominence value causes the peak to be filtered from the output.

I've defined the prominence of the highest underwater peak to be its elevation minus the elevation of the lowest saddle.  This isn't perfect, but it does give the highest peak the highest prominence value, and sort of matches the intuition of what would happen if a new, higher peak were added.

You should get the newest code, build clean, rebuild, and run with the --bathymetry flag.  I suspect this will also fix the older issue you opened.

Let me know what you find.

**Comment by anbj** [comment]
This looks really good. The results for the original grid and the +10000 grid are exactly the same:

![promtest](https://github.com/user-attachments/assets/f129fb0d-f1a4-4a66-8707-17f4d05d24a4)

So the ``--bathymetry`` switch basically says to prominence, "all the values in the input grid are < 0", right?

**Comment by akirmse** [comment]
Not exactly.  It removes the implicit sea level used when computing the
prominence of mountains on land.  It could still be useful for computing
"dry prominence", even if some of the elevations are above 0.

See
https://en.wikipedia.org/wiki/Topographic_prominence#Wet_prominence_and_dry_prominence
.

**Comment by anbj** [comment]
Right. So it's the implicit sea level that causes some discrepancy.

Thank you so much for looking into this. Let me know if I can do anything to contribute!

**Comment by anbj** [comment]
The new ``--bathymetry`` options seems to work very well! Thank you!

On some of my data, there is bad coverage. In some of these areas, the key saddle latitude and -longitude in **results.txt** is set to 0. What is rationale behind this?

![Screenshot from 2024-11-18 12-03-41](https://github.com/user-attachments/assets/8b9a7b39-c541-44c4-a958-2f3751f5ed8d)

**Comment by akirmse** [comment]
0,0 means that there is no key saddle.  For example, in your data, there is
no way to go from those high points to a higher point, staying within the
data set.

**Comment by anbj** [comment]
Right, so there is no requirement of having a key saddle. Thanks!

**Comment by akirmse** [comment]
Can this be closed now?

**Comment by anbj** [comment]
Yes. Thanks!
